apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: slowdrain
spec:
  version: {{ .TagName }}
  homepage: https://github.com/cturiel/kubectl-slowdrain
  shortDescription: Drains a Kubernetes node deleting application pods one by one with a delay
  description: |
    This plugin drains a Kubernetes node by removing application pods one by one
    with a configurable delay between each deletion. This is useful to avoid
    application downtime when draining a node with a large number of pods.
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/cturiel/kubectl-slowdrain/releases/download/{{ .TagName }}/kubectl-slowdrain_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-slowdrain
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/cturiel/kubectl-slowdrain/releases/download/{{ .TagName }}/kubectl-slowdrain_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-slowdrain
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/cturiel/kubectl-slowdrain/releases/download/{{ .TagName }}/kubectl-slowdrain_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-slowdrain
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/cturiel/kubectl-slowdrain/releases/download/{{ .TagName }}/kubectl-slowdrain_{{ .TagName }}_windows_amd64.zip" .TagName }}
    bin: kubectl-slowdrain.exe
  caveats: |
    Usage:
      $ kubectl slowdrain <node-name> --delay 30

    For additional options:
      $ kubectl slowdrain --help
      or https://github.com/cturiel/kubectl-slowdrain/blob/{{ .TagName }}/doc/USAGE.md
