apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: slowdrain
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/cturiel/kubectl-slowdrain/releases/download/v0.1.0/kubectl-slowdrain_v0.1.0_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./slowdrain"
      to: "."
    - from: LICENSE
      to: "."
    bin: "slowdrain"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/cturiel/kubectl-slowdrain/releases/download/v0.1.0/kubectl-slowdrain_v0.1.0_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./slowdrain"
      to: "."
    - from: LICENSE
      to: "."
    bin: "slowdrain"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/cturiel/kubectl-slowdrain/releases/download/v0.1.0/kubectl-slowdrain_v0.1.0_windows_amd64.zip
    sha256: ""
    files:
    - from: "/slowdrain.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "slowdrain.exe"
  shortDescription: Drains a Kubernetes node deleting application pods one by one with a delay
  homepage: https://github.com/cturiel/kubectl-slowdrain
  caveats: |
    Usage:
      $ kubectl slowdrain <node-name> --delay 30

    For additional options:
      $ kubectl slowdrain --help
      or https://github.com/cturiel/kubectl-slowdrain/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
